<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AppCliTools.CliMenu" />
    <PackageReference Include="AppCliTools.CliParameters" />
    <PackageReference Include="AppCliTools.CliParametersEdit" />
    <PackageReference Include="AppCliTools.CliParametersExcludeSetsEdit" />
    <PackageReference Include="ParametersManagement.LibFileParameters" />
    <PackageReference Include="ParametersManagement.LibParameters" />
    <PackageReference Include="SystemTools.SerilogStuff" />
    <PackageReference Include="ToolsManagement.FileManagersMain" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
